---

# Install GitKraken

- get_url: url=https://release.gitkraken.com/linux/gitkraken-amd64.deb mode=0644 validate_certs=False
  args:
    dest: "/tmp/gitkraken-amd64.deb"

- name: Install GitKraken
  apt: deb="/tmp/gitkraken-amd64.deb"
